### Handling Imbalanced Dataset

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv(r"D:\full_stack\MyPractice\eda-fe\Handling Imbalanced Dataset\Credit Card Fraud Detection\creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [7]:
df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
pd.set_option('display.max_columns', None)

In [10]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [12]:
# now we are going see our dependent features --> class


In [14]:
df["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [15]:
# it is highly imbalance data .. we have to deal with first

In [ ]:
# applying some algo on this data set without doing sampling

In [17]:
x=df.drop("Class",axis=1)
y=df.Class

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

#### note:
imbalance dataset ->  does not heavly impact ensemble techniques where decision tree is used

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV


In [19]:
10.0 **np.arange(-2,3)


array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [ ]:
# Cross Validation Like KFOLD and Hyperpaqrameter Tuning

In [23]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [24]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring="f1_macro")

In [28]:
clf.fit(x_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [36]:
y_pred=clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
# if data is imbalance then don't focus on the accuracy then only focus on the precision , recall, f1-score

[[56845    23]
 [   34    60]]
0.9989993328885924
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56868
           1       0.72      0.64      0.68        94

    accuracy                           1.00     56962
   macro avg       0.86      0.82      0.84     56962
weighted avg       1.00      1.00      1.00     56962



In [30]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [41]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[56863     5]
 [   24    70]]
0.9994908886626171
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56868
           1       0.93      0.74      0.83        94

    accuracy                           1.00     56962
   macro avg       0.97      0.87      0.91     56962
weighted avg       1.00      1.00      1.00     56962



#####  class_weight in random forest

In [37]:
class_weight=dict({0:1,1:100}) # giving more weight to that class having less value_count


In [38]:
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train,y_train)


RandomForestClassifier(class_weight={0: 1, 1: 100})

In [39]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[56863     5]
 [   26    68]]
0.9994557775359011
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56868
           1       0.93      0.72      0.81        94

    accuracy                           1.00     56962
   macro avg       0.97      0.86      0.91     56962
weighted avg       1.00      1.00      1.00     56962



## under sampling

reduce the point of the maximunm lables  (cause loss of data)

In [44]:
y_train.value_counts()

0    227447
1       398
Name: Class, dtype: int64

In [56]:
from imblearn.under_sampling import RandomUnderSampler  
from collections import Counter # does value_counts
under_sampler = RandomUnderSampler(0.80)
X_res, y_res = under_sampler.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_res)))

The number of classes before fit Counter({0: 227447, 1: 398})
The number of classes after fit Counter({0: 497, 1: 398})


In [61]:
497*0.8 # calculating manually

397.6

In [65]:
classifier=RandomForestClassifier()
classifier.fit(X_res, y_res)


RandomForestClassifier()

In [66]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[55554  1314]
 [    7    87]]
0.9768091008040448
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56868
           1       0.06      0.93      0.12        94

    accuracy                           0.98     56962
   macro avg       0.53      0.95      0.55     56962
weighted avg       1.00      0.98      0.99     56962



In [67]:
# never  do under sampling unless or untill your dataset is samll

### over sampling

In [71]:
from imblearn.over_sampling import RandomOverSampler
from collections import Counter # does value_counts
os=RandomOverSampler(0.50)
X_res, y_res = os.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_res)))

The number of classes before fit Counter({0: 227447, 1: 398})
The number of classes after fit Counter({0: 227447, 1: 113723})


In [72]:
classifier=RandomForestClassifier()
classifier.fit(X_res, y_res)

RandomForestClassifier()

In [73]:
y_pred=classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[56861     7]
 [   25    69]]
0.9994382219725431
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56868
           1       0.91      0.73      0.81        94

    accuracy                           1.00     56962
   macro avg       0.95      0.87      0.91     56962
weighted avg       1.00      1.00      1.00     56962



### SMOTETomek

it creates new points of the lowest number (near at that particular location ).i.e base on the nearest point more number of points are being created.

uses the combination of  under sampling  and over sampling .

it takes more time compare to over sampling

In [75]:

from imblearn.combine import SMOTETomek

In [88]:
from imblearn.over_sampling import SMOTE
os = SMOTE()
X_res, y_res = os.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_res)))

AttributeError: 'NoneType' object has no attribute 'split'

### Ensemble Technique


In [89]:
from imblearn.ensemble import EasyEnsembleClassifier

In [91]:
easy=EasyEnsembleClassifier()
easy.fit(x_train,y_train)

EasyEnsembleClassifier()

In [92]:
y_pred=easy.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[54738  2130]
 [    8    86]]
0.9624662055405357
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     56868
           1       0.04      0.91      0.07        94

    accuracy                           0.96     56962
   macro avg       0.52      0.94      0.53     56962
weighted avg       1.00      0.96      0.98     56962

